# Generated by Django 3.0.2 on 2020-01-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='frc_team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
