# Generated by Django 3.0.2 on 2020-01-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='frc_team',
            new_name='team',
        ),
    ]
